// =============================================
// University Data
// =============================================

export const UNIVERSITIES = [
  { id: 'mit', name: 'Massachusetts Institute of Technology', short: 'MIT', state: 'MA', type: 'private', ivy: false, tuition: 59750, enrollment: 11520, acceptanceRate: 3.9, studentFacultyRatio: 3, location: 'Cambridge, MA', color: '#A31F34', graduationRate: 96, avgSalary: 107000 },
  { id: 'stanford', name: 'Stanford University', short: 'Stanford', state: 'CA', type: 'private', ivy: false, tuition: 62484, enrollment: 9759, acceptanceRate: 3.6, studentFacultyRatio: 5, location: 'Stanford, CA', color: '#8C1515', graduationRate: 94, avgSalary: 105000 },
  { id: 'harvard', name: 'Harvard University', short: 'Harvard', state: 'MA', type: 'private', ivy: true, tuition: 59076, enrollment: 7153, acceptanceRate: 3.2, studentFacultyRatio: 5, location: 'Cambridge, MA', color: '#A51C30', graduationRate: 98, avgSalary: 95000 },
  { id: 'yale', name: 'Yale University', short: 'Yale', state: 'CT', type: 'private', ivy: true, tuition: 64700, enrollment: 6448, acceptanceRate: 4.4, studentFacultyRatio: 5, location: 'New Haven, CT', color: '#00356B', graduationRate: 97, avgSalary: 93000 },
  { id: 'columbia', name: 'Columbia University', short: 'Columbia', state: 'NY', type: 'private', ivy: true, tuition: 65524, enrollment: 8902, acceptanceRate: 3.7, studentFacultyRatio: 6, location: 'New York, NY', color: '#003B73', graduationRate: 95, avgSalary: 97000 },
  { id: 'princeton', name: 'Princeton University', short: 'Princeton', state: 'NJ', type: 'private', ivy: true, tuition: 59710, enrollment: 5548, acceptanceRate: 4.0, studentFacultyRatio: 5, location: 'Princeton, NJ', color: '#E77500', graduationRate: 98, avgSalary: 92000 },
  { id: 'caltech', name: 'California Institute of Technology', short: 'Caltech', state: 'CA', type: 'private', ivy: false, tuition: 63402, enrollment: 987, acceptanceRate: 2.7, studentFacultyRatio: 3, location: 'Pasadena, CA', color: '#FF6C0C', graduationRate: 93, avgSalary: 112000 },
  { id: 'duke', name: 'Duke University', short: 'Duke', state: 'NC', type: 'private', ivy: false, tuition: 63054, enrollment: 6883, acceptanceRate: 5.0, studentFacultyRatio: 5, location: 'Durham, NC', color: '#003087', graduationRate: 95, avgSalary: 88000 },
  { id: 'uchicago', name: 'University of Chicago', short: 'UChicago', state: 'IL', type: 'private', ivy: false, tuition: 62940, enrollment: 7526, acceptanceRate: 5.3, studentFacultyRatio: 5, location: 'Chicago, IL', color: '#800000', graduationRate: 94, avgSalary: 91000 },
  { id: 'upenn', name: 'University of Pennsylvania', short: 'UPenn', state: 'PA', type: 'private', ivy: true, tuition: 63452, enrollment: 10764, acceptanceRate: 5.5, studentFacultyRatio: 6, location: 'Philadelphia, PA', color: '#011F5B', graduationRate: 96, avgSalary: 95000 },
  { id: 'berkeley', name: 'UC Berkeley', short: 'UC Berkeley', state: 'CA', type: 'public', ivy: false, tuition: 14312, enrollment: 32143, acceptanceRate: 11.6, studentFacultyRatio: 20, location: 'Berkeley, CA', color: '#003262', graduationRate: 93, avgSalary: 85000 },
  { id: 'ucla', name: 'UCLA', short: 'UCLA', state: 'CA', type: 'public', ivy: false, tuition: 13804, enrollment: 32423, acceptanceRate: 8.7, studentFacultyRatio: 18, location: 'Los Angeles, CA', color: '#2774AE', graduationRate: 91, avgSalary: 80000 },
  { id: 'michigan', name: 'University of Michigan', short: 'Michigan', state: 'MI', type: 'public', ivy: false, tuition: 16736, enrollment: 33088, acceptanceRate: 17.7, studentFacultyRatio: 15, location: 'Ann Arbor, MI', color: '#00274C', graduationRate: 92, avgSalary: 76000 },
  { id: 'uva', name: 'University of Virginia', short: 'UVA', state: 'VA', type: 'public', ivy: false, tuition: 19814, enrollment: 17299, acceptanceRate: 18.7, studentFacultyRatio: 14, location: 'Charlottesville, VA', color: '#232D4B', graduationRate: 94, avgSalary: 78000 },
  { id: 'gatech', name: 'Georgia Institute of Technology', short: 'Georgia Tech', state: 'GA', type: 'public', ivy: false, tuition: 12682, enrollment: 18831, acceptanceRate: 16.4, studentFacultyRatio: 18, location: 'Atlanta, GA', color: '#B3A369', graduationRate: 90, avgSalary: 82000 },
  { id: 'utexas', name: 'University of Texas at Austin', short: 'UT Austin', state: 'TX', type: 'public', ivy: false, tuition: 11448, enrollment: 40916, acceptanceRate: 29.1, studentFacultyRatio: 17, location: 'Austin, TX', color: '#BF5700', graduationRate: 88, avgSalary: 74000 },
  { id: 'cornell', name: 'Cornell University', short: 'Cornell', state: 'NY', type: 'private', ivy: true, tuition: 63200, enrollment: 15735, acceptanceRate: 7.5, studentFacultyRatio: 9, location: 'Ithaca, NY', color: '#B31B1B', graduationRate: 94, avgSalary: 87000 },
  { id: 'dartmouth', name: 'Dartmouth College', short: 'Dartmouth', state: 'NH', type: 'private', ivy: true, tuition: 62430, enrollment: 4556, acceptanceRate: 6.2, studentFacultyRatio: 7, location: 'Hanover, NH', color: '#00693E', graduationRate: 96, avgSalary: 85000 },
  { id: 'brown', name: 'Brown University', short: 'Brown', state: 'RI', type: 'private', ivy: true, tuition: 65146, enrollment: 7160, acceptanceRate: 5.1, studentFacultyRatio: 6, location: 'Providence, RI', color: '#4E3629', graduationRate: 95, avgSalary: 82000 },
  { id: 'nyu', name: 'New York University', short: 'NYU', state: 'NY', type: 'private', ivy: false, tuition: 58168, enrollment: 29401, acceptanceRate: 12.2, studentFacultyRatio: 8, location: 'New York, NY', color: '#57068C', graduationRate: 85, avgSalary: 84000 },
];
